"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OAUTH_PROVIDERS = exports.HOSTED_BOUNCE_URL = exports.RELAY_BASE = void 0;
exports.oauthProvider = oauthProvider;
// Build-time-inlined first-party client creds (generated by scripts/gen-hosted-config.mjs from a
// local .env or CI secrets). Baked in so packaged builds work — tsc-compiled `process.env` reads do
// not survive to end-user machines. Env still overrides at runtime for dev/self-host flexibility.
const hostedConfig_1 = require("../../generated/hostedConfig");
/**
 * Base URL of the Tier-C vendor relay (see docs/channel_implementation/vendor_relay.md). Override via
 * env for self-hosted relays / local dev. The default is the hosted production relay we operate.
 */
exports.RELAY_BASE = (process.env.MARKETING_RELAY_BASE || 'https://relay.1marketingtool.app').replace(/\/+$/, '');
/**
 * Hosted HTTPS → loopback redirect bounce for BYO providers whose platform rejects the
 * `http://127.0.0.1` loopback redirect (Facebook, Pinterest). The user registers this single URL in
 * their own app; it 302-bounces `?code&state` to our loopback listener. Stateless + secret-less — the
 * desktop still exchanges the code with the user's own secret. See docs/channel_implementation/
 * byo_https_redirect.md and 1MarketingTool/oauth-bounce/. Override via env for local dev.
 */
exports.HOSTED_BOUNCE_URL = (process.env.MARKETING_OAUTH_BOUNCE || 'https://oauth.1marketingtool.com/cb').replace(/\/+$/, '');
/** BYO OAuth2 providers — the user registers their own app; we only orchestrate the flow. */
exports.OAUTH_PROVIDERS = {
    // Hosted "Sign in with Google" for the Search Console / GA4 data connector. Unlike the BYO
    // channels, the client id/secret are ours (embedded from build env) so the user clicks once and
    // sets up nothing. Read-only scopes only (index submission stays on the service account). The
    // access_type=offline + prompt=consent pair makes Google return a refresh_token so the connection
    // silently auto-renews. Uses the loopback redirect (Desktop-app client) — no bounce/relay.
    google_search_console: {
        name: 'google_search_console',
        authorizeUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
        tokenUrl: 'https://oauth2.googleapis.com/token',
        scopes: [
            'openid',
            'https://www.googleapis.com/auth/userinfo.email',
            'https://www.googleapis.com/auth/webmasters.readonly',
            'https://www.googleapis.com/auth/analytics.readonly',
        ],
        clientAuth: 'body',
        usePkce: true,
        extraAuthParams: { access_type: 'offline', prompt: 'consent' },
        hosted: {
            clientId: process.env.MARKETING_GOOGLE_CLIENT_ID || hostedConfig_1.HOSTED_CONFIG.googleClientId,
            clientSecret: process.env.MARKETING_GOOGLE_CLIENT_SECRET || hostedConfig_1.HOSTED_CONFIG.googleClientSecret,
        },
        identity: { url: 'https://www.googleapis.com/oauth2/v3/userinfo', field: 'email' },
    },
    linkedin: {
        name: 'linkedin',
        authorizeUrl: 'https://www.linkedin.com/oauth/v2/authorization',
        tokenUrl: 'https://www.linkedin.com/oauth/v2/accessToken',
        // OpenID Connect (sign-in + member id) + Share on LinkedIn (post on the member's behalf).
        scopes: ['openid', 'profile', 'w_member_social'],
        clientAuth: 'body',
        usePkce: false,
        identity: { url: 'https://api.linkedin.com/v2/userinfo', field: 'name' },
    },
    pinterest: {
        name: 'pinterest',
        authorizeUrl: 'https://www.pinterest.com/oauth/',
        tokenUrl: 'https://api.pinterest.com/v5/oauth/token',
        scopes: ['boards:read', 'boards:write', 'pins:read', 'pins:write', 'user_accounts:read'],
        clientAuth: 'basic',
        usePkce: false,
        scopeSeparator: ',',
        // Pinterest v5 rejects the loopback redirect — route through the hosted HTTPS bounce.
        httpsRedirect: true,
        identity: { url: 'https://api.pinterest.com/v5/user_account', field: 'username' },
    },
    youtube: {
        name: 'youtube',
        authorizeUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
        tokenUrl: 'https://oauth2.googleapis.com/token',
        scopes: [
            'openid',
            'https://www.googleapis.com/auth/userinfo.profile',
            'https://www.googleapis.com/auth/youtube.upload',
        ],
        optionalScopes: [
            'https://www.googleapis.com/auth/youtube.readonly',
            'https://www.googleapis.com/auth/yt-analytics.readonly',
            'https://www.googleapis.com/auth/youtube.force-ssl',
        ],
        clientAuth: 'body',
        usePkce: true,
        // access_type=offline + prompt=consent are required for Google to return a refresh token.
        extraAuthParams: { access_type: 'offline', prompt: 'consent' },
        // Hosted by default: our verified Google app (project 465529858179, approved for youtube.upload +
        // youtube.readonly) is embedded from build env, so the user connects in one click with nothing to
        // register. Uses the loopback redirect (Desktop-app client) — same as google_search_console. A power
        // user can still paste their own Client ID + Secret (catalog secretFields) to run through their own
        // Google app: resolveClientCreds prefers saved user creds over the hosted ones when both exist.
        hosted: {
            clientId: process.env.MARKETING_GOOGLE_CLIENT_ID || hostedConfig_1.HOSTED_CONFIG.googleClientId,
            clientSecret: process.env.MARKETING_GOOGLE_CLIENT_SECRET || hostedConfig_1.HOSTED_CONFIG.googleClientSecret,
        },
        identity: { url: 'https://www.googleapis.com/oauth2/v3/userinfo', field: 'name' },
    },
    tiktok: {
        name: 'tiktok',
        authorizeUrl: 'https://www.tiktok.com/v2/auth/authorize/',
        tokenUrl: 'https://open.tiktokapis.com/v2/oauth/token/',
        scopes: ['user.info.basic', 'video.upload'],
        optionalScopes: ['video.list'],
        clientAuth: 'body',
        clientIdParam: 'client_key',
        usePkce: true,
        scopeSeparator: ',',
        httpsRedirect: true,
    },
    // BYO — the user registers their own Meta app (Development mode posts to Pages they admin, no App
    // Review). Facebook rejects the loopback redirect, so it routes through the hosted HTTPS bounce;
    // the code exchange returns a short-lived token that we extend to ~60 days (fb_exchange_token).
    facebook: {
        name: 'facebook',
        authorizeUrl: 'https://www.facebook.com/v23.0/dialog/oauth',
        tokenUrl: 'https://graph.facebook.com/v23.0/oauth/access_token',
        // Keep the established Page publisher contract stable. Insights/engagement are an explicit
        // Distribution Performance upgrade because Meta rejects scopes the user's app has not added.
        scopes: ['pages_show_list', 'pages_read_engagement', 'pages_manage_posts'],
        optionalScopes: ['read_insights', 'pages_manage_engagement'],
        clientAuth: 'body',
        usePkce: false,
        scopeSeparator: ',',
        httpsRedirect: true,
        longLived: {
            url: 'https://graph.facebook.com/v23.0/oauth/access_token',
            grantType: 'fb_exchange_token',
            tokenParam: 'fb_exchange_token',
            sendClientId: true,
        },
        identity: { url: 'https://graph.facebook.com/v23.0/me?fields=name', field: 'name' },
    },
    // BYO — "Instagram API with Instagram login". The Facebook-login path for Instagram is dead: the old
    // instagram_basic / instagram_content_publish names were retired, and their instagram_business_*
    // replacements are ONLY valid on Instagram's own login dialog — facebook.com/dialog/oauth rejects them
    // as "Invalid Scopes". So Instagram needs its OWN Instagram App ID + Secret (from the app's Instagram
    // business-login setup, NOT the Facebook App ID), its own auth host (instagram.com), token host
    // (api.instagram.com) and graph host (graph.instagram.com). No Facebook Page — publishing targets the
    // connected IG professional account directly. Still routes through the hosted HTTPS bounce.
    instagram: {
        name: 'instagram',
        authorizeUrl: 'https://www.instagram.com/oauth/authorize',
        tokenUrl: 'https://api.instagram.com/oauth/access_token',
        scopes: [
            'instagram_business_basic',
            'instagram_business_content_publish',
        ],
        optionalScopes: [
            'instagram_business_manage_insights',
            'instagram_business_manage_comments',
        ],
        clientAuth: 'body',
        usePkce: false,
        scopeSeparator: ',',
        httpsRedirect: true,
        // Short-lived (~1h) token from the code exchange → ~60-day long-lived one via ig_exchange_token
        // (client_secret only, no client_id — the same shape as Threads' th_exchange_token).
        longLived: {
            url: 'https://graph.instagram.com/access_token',
            grantType: 'ig_exchange_token',
            tokenParam: 'access_token',
            sendClientId: false,
        },
        identity: { url: 'https://graph.instagram.com/me?fields=username', field: 'username' },
    },
    // BYO — the user registers their own Meta app with the Threads use case (its own Threads App ID +
    // Secret, distinct from Facebook Login). Threads has its own OAuth host (threads.net) + token host
    // (graph.threads.net) and rejects the loopback redirect, so it routes through the hosted HTTPS bounce
    // (same as Facebook). The code exchange returns a short-lived token that we extend to a ~60-day
    // long-lived one via `th_exchange_token` (Threads' analogue of Facebook's `fb_exchange_token`).
    // Endpoints mirror relay/src/threads.ts. No relay — the desktop exchanges with the user's own secret.
    threads: {
        name: 'threads',
        authorizeUrl: 'https://threads.net/oauth/authorize',
        tokenUrl: 'https://graph.threads.net/oauth/access_token',
        scopes: [
            'threads_basic',
            'threads_content_publish',
        ],
        optionalScopes: [
            'threads_manage_replies',
            'threads_manage_insights',
            'threads_read_replies',
        ],
        clientAuth: 'body',
        usePkce: false,
        scopeSeparator: ',',
        httpsRedirect: true,
        longLived: {
            url: 'https://graph.threads.net/access_token',
            grantType: 'th_exchange_token',
            tokenParam: 'access_token',
            sendClientId: false,
        },
        identity: { url: 'https://graph.threads.net/v1.0/me?fields=username', field: 'username' },
    },
};
function oauthProvider(name) {
    return exports.OAUTH_PROVIDERS[name] ?? null;
}
//# sourceMappingURL=providers.js.map